Charzy portfolio/project gallery
Charzy-1/My-Portfolio-Website pull request #1
Opened 2024-05-09 21:57 UTC by Charzy-1

html and css files was created and codes were added respectively
linters were configured but abolutely unable to fix the bug that pops up on stylint
readme was modified but not yet complete
The interface i try to build is not yet aligned.

2024-05-09 22:03 UTC, Charzy-1 commented
Hi @basitali111 and mkp please rescue me in fixing the stylint linters and a betterway to code in getting the template  i try to get. Also making my site responsive is tough.

Thanks for your responses in advance

2024-05-10 08:22 UTC, basitali111 commented
Kindly share me timings when you are available ?


On Fri, May 10, 2024 at 3:03 AM Charles Adikankwu ***@***.***>
wrote:

> Hi @basitali111 <https://github.com/basitali111> and mkp please rescue me
> in fixing the stylint linters and a betterway to code in getting the
> template i try to get. Also making my site responsive is tough.
>
> Thanks for your responses in advance
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Charzy-1/My-Portfolio-Website/pull/1#issuecomment-2103486014>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APBEPJI3AZWOUFFPT4A2ZB3ZBPXETAVCNFSM6AAAAABHPRTWH2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMBTGQ4DMMBRGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-10 09:07 UTC, Charzy-1 commented
Ok. We can meet the same time (8pm) we normally use to meet.

Thanks & Regards

On Fri, 10 May 2024, 11:22 am Basit Ali, ***@***.***> wrote:

> Kindly share me timings when you are available ?
>
>
> On Fri, May 10, 2024 at 3:03 AM Charles Adikankwu ***@***.***>
> wrote:
>
> > Hi @basitali111 <https://github.com/basitali111> and mkp please rescue
> me
> > in fixing the stylint linters and a betterway to code in getting the
> > template i try to get. Also making my site responsive is tough.
> >
> > Thanks for your responses in advance
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/Charzy-1/My-Portfolio-Website/pull/1#issuecomment-2103486014>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/APBEPJI3AZWOUFFPT4A2ZB3ZBPXETAVCNFSM6AAAAABHPRTWH2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMBTGQ4DMMBRGQ>
>
> > .
> > You are receiving this because you were mentioned.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Charzy-1/My-Portfolio-Website/pull/1#issuecomment-2104167452>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU552SUAZKSOL2YNIU2H5STZBR7T3AVCNFSM6AAAAABHPRTWH2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMBUGE3DONBVGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-10 09:35 UTC, basitali111 commented
Hello,

I understand. I will see you then. However, I would like to encourage you
to try to resolve the issue on your own. You have done most of the research
and error-solving for your project, so I believe you are capable of
handling this.

Please try your best to resolve the issue before our meeting. This will
help us avoid wasting time and repetition.

Thank you for your understanding.

Best regards
Basit Ali


On Fri, May 10, 2024, 2:07 PM Charles Adikankwu ***@***.***>
wrote:

> Ok. We can meet the same time (8pm) we normally use to meet.
>
> Thanks & Regards
>
> On Fri, 10 May 2024, 11:22 am Basit Ali, ***@***.***> wrote:
>
> > Kindly share me timings when you are available ?
> >
> >
> > On Fri, May 10, 2024 at 3:03 AM Charles Adikankwu ***@***.***>
> > wrote:
> >
> > > Hi @basitali111 <https://github.com/basitali111> and mkp please
> rescue
> > me
> > > in fixing the stylint linters and a betterway to code in getting the
> > > template i try to get. Also making my site responsive is tough.
> > >
> > > Thanks for your responses in advance
> > >
> > > —
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/Charzy-1/My-Portfolio-Website/pull/1#issuecomment-2103486014>,
>
> >
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/APBEPJI3AZWOUFFPT4A2ZB3ZBPXETAVCNFSM6AAAAABHPRTWH2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMBTGQ4DMMBRGQ>
>
> >
> > > .
> > > You are receiving this because you were mentioned.Message ID:
> > > ***@***.***>
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/Charzy-1/My-Portfolio-Website/pull/1#issuecomment-2104167452>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AU552SUAZKSOL2YNIU2H5STZBR7T3AVCNFSM6AAAAABHPRTWH2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMBUGE3DONBVGI>
>
> > .
> > You are receiving this because you authored the thread.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Charzy-1/My-Portfolio-Website/pull/1#issuecomment-2104240318>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APBEPJKJH4VP752UBWYA7OTZBSE5JAVCNFSM6AAAAABHPRTWH2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMBUGI2DAMZRHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-10 09:42 UTC, Charzy-1 commented
I will always try my best. The error message is almost same for the various
style block. I know that when I am able to fix one, I will be 70% good to
go in fixing others. I just still hovering around it.

See you soon.

On Fri, 10 May 2024, 12:35 pm Basit Ali, ***@***.***> wrote:

> Hello,
>
> I understand. I will see you then. However, I would like to encourage you
> to try to resolve the issue on your own. You have done most of the
> research
> and error-solving for your project, so I believe you are capable of
> handling this.
>
> Please try your best to resolve the issue before our meeting. This will
> help us avoid wasting time and repetition.
>
> Thank you for your understanding.
>
> Best regards
> Basit Ali
>
>
> On Fri, May 10, 2024, 2:07 PM Charles Adikankwu ***@***.***>
> wrote:
>
> > Ok. We can meet the same time (8pm) we normally use to meet.
> >
> > Thanks & Regards
> >
> > On Fri, 10 May 2024, 11:22 am Basit Ali, ***@***.***> wrote:
> >
> > > Kindly share me timings when you are available ?
> > >
> > >
> > > On Fri, May 10, 2024 at 3:03 AM Charles Adikankwu ***@***.***>
> > > wrote:
> > >
> > > > Hi @basitali111 <https://github.com/basitali111> and mkp please
> > rescue
> > > me
> > > > in fixing the stylint linters and a betterway to code in getting the
> > > > template i try to get. Also making my site responsive is tough.
> > > >
> > > > Thanks for your responses in advance
> > > >
> > > > —
> > > > Reply to this email directly, view it on GitHub
> > > > <
> > >
> >
> https://github.com/Charzy-1/My-Portfolio-Website/pull/1#issuecomment-2103486014>,
>
> >
> > >
> > > > or unsubscribe
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe-auth/APBEPJI3AZWOUFFPT4A2ZB3ZBPXETAVCNFSM6AAAAABHPRTWH2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMBTGQ4DMMBRGQ>
>
> >
> > >
> > > > .
> > > > You are receiving this because you were mentioned.Message ID:
> > > > ***@***.***>
> > > >
> > >
> > > —
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/Charzy-1/My-Portfolio-Website/pull/1#issuecomment-2104167452>,
>
> >
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/AU552SUAZKSOL2YNIU2H5STZBR7T3AVCNFSM6AAAAABHPRTWH2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMBUGE3DONBVGI>
>
> >
> > > .
> > > You are receiving this because you authored the thread.Message ID:
> > > ***@***.***>
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/Charzy-1/My-Portfolio-Website/pull/1#issuecomment-2104240318>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/APBEPJKJH4VP752UBWYA7OTZBSE5JAVCNFSM6AAAAABHPRTWH2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMBUGI2DAMZRHA>
>
> > .
> > You are receiving this because you were mentioned.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Charzy-1/My-Portfolio-Website/pull/1#issuecomment-2104283722>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU552SRPTZZ4ONHORA2ZNBTZBSIGLAVCNFSM6AAAAABHPRTWH2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMBUGI4DGNZSGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-10 20:45 UTC, Charzy-1 commented
Hi. @basitali111 Thanks for your assistance thus far.

Please have a recheck on the pull request again and give me feedback.

2024-05-11 09:29 UTC, basitali111 requested changes
# Required Changes ♻️
Hi @Charzy-1 ,
Good job so far!
![Apex_1715419212206](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/e8fe3a2a-e848-4300-b625-78105b96f4ad)
- **Its your design** 
- **But the design you have to make is this:**
![Apex_1715419473638](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/9343673f-1fed-4acf-92af-e21431b2dde7)
- **remember, it should be responsive here is project requiremnet on itsee it care fully and follow the instruction**
-The website should be responsive, following these breakpoints:
- Minimum mobile screen size should be 375px
- Minimum desktop screen size should be 768px
- Use responsive values in your CSS rules, like percentages (i.e. width: 80%),
instead of pixels



There are some issues that you still need to work on to go to the next project but you are almost there!
159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff

## Highlights
✔️ No Linters errors
✔️ Professional Readme
✔️ Correct Gitflow

## Required
 Check the comments under the review.
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@basitali111] in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2024-05-11 09:29 UTC, basitali111 commented on styles.css
> +
* {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
}
- Kindly try to use on top of your stylesheet to git rid of the extra by default space around your webpage so your design become better

2024-05-11 10:09 UTC, Charzy-1 commented
Thanks for the feedback! I will correct it

On Sat, 11 May 2024, 12:29 pm Basit Ali, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> Required Changes ♻️
>
> Hi @Charzy-1 <https://github.com/Charzy-1> ,
> Good job so far!
> Apex_1715419212206.png (view on web)
> <https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/e8fe3a2a-e848-4300-b625-78105b96f4ad>
>
>    - *Its your design*
>    - *But the design you have to make is this:*
>    Apex_1715419473638.png (view on web)
>    <https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/9343673f-1fed-4acf-92af-e21431b2dde7>
>    - *remember, it should be responsive here is project requiremnet on
>    itsee it care fully and follow the instruction*
>    -The website should be responsive, following these breakpoints:
>    - Minimum mobile screen size should be 375px
>    - Minimum desktop screen size should be 768px
>    - Use responsive values in your CSS rules, like percentages (i.e.
>    width: 80%),
>    instead of pixels
>
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> 159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff
> Highlights
>
> ✔️ No Linters errors
> ✔️ Professional Readme
> ✔️ Correct Gitflow
> Required
>
> Check the comments under the review.
> Optional suggestions
> Every comment with the [OPTIONAL] prefix is not crucial enough to stop the
> approval of this PR. However, I strongly recommend you to take them into
> account as they can make your code better.
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me ***@***.*** <https://github.com/basitali111>]
> in your question so I can receive the notification.
>
> Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.
> ------------------------------
>
> In styles.css
> <https://github.com/Charzy-1/My-Portfolio-Website/pull/1#discussion_r1597407155>
> :
>
> > +body {
> +  font-family: sans-serif;
> +  margin: 0;
> +}
> +
>
>
>    - {
>    box-sizing: border-box;
>    padding: 0;
>    margin: 0;
>    }
>
>
>    - Kindly try to use on top of your stylesheet to git rid of the extra
>    by default space around your webpage so your design become better
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Charzy-1/My-Portfolio-Website/pull/1#pullrequestreview-2051163506>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU552SVZM65NCQEMRGMB2KTZBXQJFAVCNFSM6AAAAABHPRTWH2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANJRGE3DGNJQGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-12 20:19 UTC, Charzy-1 commented
Hi @basitali111  
I have made some necessary corrections on the first part of the assignment. Kindly have a look.

2024-05-13 19:19 UTC, basitali111 requested changes
# Required Changes ♻️
Hi @Charzy-1 ,
Good job so far!
![Apex_1715419212206](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/e8fe3a2a-e848-4300-b625-78105b96f4ad)
![Apex_1715627208671](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/ce2a7e88-fb66-4487-bbaa-a5661590b25f)

#  **Its your design for mobile and desktop  ** 
# But the design you have to make is this:
## For Desktop:
![Apex_1715419473638](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/9343673f-1fed-4acf-92af-e21431b2dde7)
## For Mobile
- Make a hamburger menu so in mobile size when it click menu appear and when you click it gone 
- For Helping try to use this to research on youtube how to make this ( **How to create a responsive navbar with hamburger menu** )
![Apex_1715627109076](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/93b71128-a9c2-4364-bff8-a18272ded679)

- **remember, it should be responsive here is project requirements on it see it carefully and follow the instruction**
-The website should be responsive, following these breakpoints:
- Minimum mobile screen size should be 375px
- Minimum desktop screen size should be 768px
- Use responsive values in your CSS rules, like percentages (i.e. width: 80%),
instead of pixels



There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ No Linters errors
✔️ Professional Readme
✔️ Correct Gitflow

## Required
 Check the comments under the review.
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@basitali111] in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2024-05-13 19:19 UTC, basitali111 commented on styles.css
> +}
- Kindly already we told do not use width in px always use width percentage so your webpage got responsive 
and also remove padding and margin to remove extra white space around the webpage

2024-05-13 19:19 UTC, basitali111 commented on images/lnkdn.jpg
- one more thing kindly try to download this file in correct way so you can use as same as in figma

[Apex_1715627879775.webm](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/22eb977e-2dd1-4faa-aa9f-8f3d75ccdb89)

2024-05-13 22:09 UTC, Charzy-1 commented
Thanks for the feedbak. I will appreciate if you can review the second pull request so i can see to the corrections tommorrow. Meanwhile, can we meet so i will be assisted in figuring out some things going forward?

2024-05-14 21:54 UTC, Charzy-1 commented
Hi @basitali111. Thanks thus far
Kindly have a look of my assignment 1 again.

2024-05-15 06:16 UTC, Charzy-1 commented
Please don't review yet let me finish the mobile version

2024-05-15 08:02 UTC, basitali111 commented
Ok, no problem.

On Wed, May 15, 2024 at 11:17 AM Charles Adikankwu ***@***.***>
wrote:

> Please don't review yet let me finish the mobile version
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Charzy-1/My-Portfolio-Website/pull/1#issuecomment-2111666665>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APBEPJMZU3LN4SS2FKT4CSLZCL4WVAVCNFSM6AAAAABHPRTWH2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMJRGY3DMNRWGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-15 08:16 UTC, Charzy-1 commented
Please is it possible for us to meet? I want you to assist me in fixing
some error i ran into trying to make a mobile version

On Wed, 15 May 2024 at 11:02, Basit Ali ***@***.***> wrote:

> Ok, no problem.
>
> On Wed, May 15, 2024 at 11:17 AM Charles Adikankwu ***@***.***>
> wrote:
>
> > Please don't review yet let me finish the mobile version
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/Charzy-1/My-Portfolio-Website/pull/1#issuecomment-2111666665>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/APBEPJMZU3LN4SS2FKT4CSLZCL4WVAVCNFSM6AAAAABHPRTWH2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMJRGY3DMNRWGU>
>
> > .
> > You are receiving this because you were mentioned.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Charzy-1/My-Portfolio-Website/pull/1#issuecomment-2111838055>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU552SUDSDR3THWSM5FDQDLZCMJCXAVCNFSM6AAAAABHPRTWH2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMJRHAZTQMBVGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-15 15:47 UTC, Charzy-1 commented
Hi @basitali111 i have tried the best i could to do get what was required. Only the placement of the banner image on my mobile is what i couldn't figure out. Please review my code and see if it is what i can go ahead with.

2024-05-15 17:29 UTC, basitali111 requested changes
# Required Changes ♻️

Hi @Charzy-1 ,

- First of all, in your navbar in mobile size the `menu `should be hidden and only appear when the user clicks on 3 dots on the navbar in mobile size  so in my recommendation what you can do is use `display: none` in `media query` and hide the menus of desktop and make a separate menu for mobile
![Apex_1715794257519](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/d470b009-753b-477a-b471-2a422d9a7483)

-  Secondly, in the navbar, your menu is not equally centered kindly try to center it.
![Apex_1715793223200](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/302ee547-8bc5-4dfc-881c-d8eefe141144)
- thirdly your website is not taking up whole space on the desktop size I think you can work on height also and make height responsive
![Apex_1715793481717](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/e91e2e23-e103-4e59-8f9b-6aaa037fe25a)
- Also fix your image by doing some research because it's good for you in the real world these minors even junior programmers have to solve by themselves if you still find it difficult let me know we arrange a meeting.
Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!
![159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff](https://github.com/Charzy-1/Hello-world/assets/63063973/dcaf3754-f90d-4bb2-ba76-03e5d01a282d)
# Highlights
✔️ Professional Readme
✔️ Correct Gitflow
✔️ Linters pass
## Required 
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@basitali111] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2024-05-17 21:04 UTC, Charzy-1 commented
Hi @basitali111 . kindly review my work.

2024-05-18 06:39 UTC, basitali111 requested changes
# Required Changes ♻️
Hi @Charzy-1 ,
Good job so far!
## You are almost finished. Please work on the mobile version.
![Apex_1716013607462](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/9ae32772-22c3-4a9e-9a70-6c2ee06589ae)
## Here is your design. You just have to work on the icons and mobile image to make them responsive.
![Apex_1716014080259](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/61d953dd-1f1a-42bf-8f26-87c02ff1fd9c)

There are still some issues that need to be addressed before moving on to the next project, but you are almost there!

![giphy_2](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/9f6ce91b-4820-4b02-81fb-b2d7711336fa)


## Highlights
✔️ No Linters errors
✔️ Professional Readme
✔️ Correct Gitflow

## Required
 Check the comments under the review.
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@basitali111] in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2024-05-18 18:35 UTC, Charzy-1 commented
Hi @basitali111 
Please check again. Thanks

2024-05-19 10:19 UTC, basitali111 requested changes
# Required Changes ♻️
Hi @Charzy-1 ,
Good job so far!
## You are almost finished. Please You need to still work on the mobile version Specially on icons because when I go to mobile size the icons goes far from text kindly fix that.
![Screenshot 2024-05-19 150618.png](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/e932dedf-a7ff-4564-a2a3-9c52c478ffd4)

## Also work on the humburgue menu because it is not look like Figma design kindly  look at that and try to make like that:

![IMG-20240519-WA0015.jpg](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/dcc79397-9478-4b8b-bea6-6e481586aa93)





There are still some issues that need to be addressed before moving on to the next project, but you are almost there!

![giphy_2](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/9f6ce91b-4820-4b02-81fb-b2d7711336fa)


## Highlights
✔️ No Linters errors
✔️ Professional Readme
✔️ Correct Gitflow

## Required
 Check the comments under the review.
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@basitali111] in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2024-05-19 12:00 UTC, Charzy-1 commented
Ok. Please check again. @basitali111

2024-05-19 12:09 UTC, Charzy-1 commented
Hi. Please check my code again. Thanks

On Sun, 19 May 2024 at 13:19, Basit Ali ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> Required Changes ♻️
>
> Hi @Charzy-1 <https://github.com/Charzy-1> ,
> Good job so far!
> You are almost finished. Please You need to still work on the mobile
> version Specially on icons because when I go to mobile size the icons goes
> far from text kindly fix that.
>
> Screenshot.2024-05-19.150618.png (view on web)
> <https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/e932dedf-a7ff-4564-a2a3-9c52c478ffd4>
> Also work on the humburgue menu because it is not look like Figma design
> kindly look at that and try to make like that:
>
> IMG-20240519-WA0015.jpg (view on web)
> <https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/dcc79397-9478-4b8b-bea6-6e481586aa93>
>
> There are still some issues that need to be addressed before moving on to
> the next project, but you are almost there!
>
> giphy_2.gif (view on web)
> <https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/9f6ce91b-4820-4b02-81fb-b2d7711336fa>
> Highlights
>
> ✔️ No Linters errors
> ✔️ Professional Readme
> ✔️ Correct Gitflow
> Required
>
> Check the comments under the review.
> Optional suggestions
> Every comment with the [OPTIONAL] prefix is not crucial enough to stop the
> approval of this PR. However, I strongly recommend you to take them into
> account as they can make your code better.
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me ***@***.*** <https://github.com/basitali111>]
> in your question so I can receive the notification.
>
> Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Charzy-1/My-Portfolio-Website/pull/1#pullrequestreview-2065042900>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU552SX2Z3RL5CTLQCULVHDZDB4DNAVCNFSM6AAAAABHPRTWH2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANRVGA2DEOJQGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-19 12:39 UTC, Charzy-1 commented
Hi. I am still here

2024-05-19 18:04 UTC, basitali111 requested changes
# Required Changes ♻️
Hi @Charzy-1 ,
Good job so far!
## You are nearly done. Please work on the mobile version, especially the icons. When I switch to mobile size, the icons move far from the text. Please fix this.
### Recommendation:
- During checking, ensure that the content fits all mobile sizes, including small mobiles where the main issues are with icons and images.
![Apex_1716141293302](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/b641d680-61be-4a2f-a610-25b3868dfe1b)

## Design that you have to make is this :
![Apex_1716140815189](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/e6ca20ef-8d84-497b-977c-2052797e4346)


## Work on the hamburger menu as it doesn't match Figma's design. Please review and adjust accordingly.

![Apex_1716140694538](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/57c7b9fc-5e0a-4b89-9e97-5bf8b54a3b6a)






There are still some issues that need to be addressed before moving on to the next project, but you are almost there!

![giphy_2](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/9f6ce91b-4820-4b02-81fb-b2d7711336fa)


## Highlights
✔️ No Linters errors
✔️ Professional Readme
✔️ Correct Gitflow

## Required
 Check the comments under the review.
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@basitali111] in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2024-05-19 22:57 UTC, Charzy-1 commented
Please kindly check for the modification of image, social icon respnosiveness and hambuger @basitali111

2024-05-20 06:26 UTC, basitali111 requested changes
# Required Changes ♻️
Hi @Charzy-1 ,
Good job so far!
## You are almost finished. Please work on the mobile version, particularly the icons. When I switch to mobile size, the icons move too far from the text. Please address this. Also, please review the following video.

[Apex_1716186312659.webm](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/6f98a16f-2f3a-4a52-84c9-5f1ac912f469)


There are still some issues that need to be addressed before moving on to the next project, but you are almost there!

![giphy_2](https://github.com/Charzy-1/My-Portfolio-Website/assets/63063973/9f6ce91b-4820-4b02-81fb-b2d7711336fa)


## Highlights
✔️ No Linters errors
✔️ Professional Readme
✔️ Correct Gitflow

## Required
 Check the comments under the review.
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@basitali111] in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2024-05-20 16:46 UTC, Charzy-1 commented
Hi @basitali111 I have modified the CSS with the recommendations given for the mobile responsiveness

2024-05-20 17:46 UTC, basitali111 approved these changes
# Approve 🟢 🟢 🟢 
Hi @Charzy-1,  

Your project is complete!  There is nothing else to say other than... it's time to merge it :ship: 

- [Optional] Kindly ensure that your pull request title and description are well-written next time."
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀  
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @basitali111.

2024-05-20 18:05 UTC, Charzy-1 commented
Thanks for the feedback!

On Mon, 20 May 2024 at 20:47, Basit Ali ***@***.***> wrote:

> ***@***.**** approved this pull request.
> Approve 🟢 🟢 🟢
>
> Hi @Charzy-1 <https://github.com/Charzy-1>,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it 🚢
>
>    - [Optional] Kindly ensure that your pull request title and
>    description are well-written next time."
>    Congratulations! 🎉
>
> Highlights
>
>    - No linter errors ✅
>    - Git flow was used correctly 🚀
>    - Good Pr title and description 💪🏿
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification @basitali111 <https://github.com/basitali111>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Charzy-1/My-Portfolio-Website/pull/1#pullrequestreview-2066702858>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU552SQ42PI7MGUAKE44PHLZDIZKPAVCNFSM6AAAAABHPRTWH2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANRWG4YDEOBVHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-20 18:06 UTC, merged