Portfolio/popup window
Charzy-1/My-Portfolio-Website pull request #7
Opened 2024-06-12 15:09 UTC by Charzy-1

I used Js DOM to create a pop-up window when my see project is clicked
I added another image to the section of the pop-up window
i made the window responsive to all possible given screens

2024-06-13 11:37 UTC, Charzy-1 commented
Modifications were made to correct linters error

2024-06-13 16:33 UTC, basitali111 requested changes
# Required Changes ♻️

Hi @Charzy-1 ,

- Please read the project requirements carefully before submitting your pull request. The requirements clearly mention that the popup should work for all projects in the portfolio section. Additionally, update your portfolio section to dynamically create all projects using a for loop or similar method.
**-In order to associate each project with the popup window details, you must refactor the project section:
o You need to use a JavaScript array to store all of the information for all projects.
o For each project you need to store the following pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, link to source.
o You need to update the main page so that the projects section is created dynamically using the information stored in that JavaScript object. Remember, all of the HTML in that section is created when the page loads.
o After that, you could implement the popup window.
• You should implement popups for both mobile and desktop screen sizes.**

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!
![159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff](https://github.com/Charzy-1/Hello-world/assets/63063973/dcaf3754-f90d-4bb2-ba76-03e5d01a282d)
# Highlights
✔️ Professional Readme
✔️ Correct Gitflow
✔️ Linters pass
## Required 
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@basitali111] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2024-06-18 16:51 UTC, Charzy-1 commented
Modifications were made in all three files to implement popup window.
open popup function was created with an argument of id passed into it to open popup in javascript
objects were creaated where captured dynamically using the id's

2024-06-18 18:32 UTC, basitali111 requested changes
# Required Changes ♻️

Hi @Charzy-1 ,
- Kindly remove the project card and popup from index.html and transfer them to your JS file. Kindly, tomorrow is just a demonstration, but please adhere strictly to the project requirements.
- "Also, when clicking on the 'see project' button, the page should move upward. Please fix this issue."
- Please read the project requirements carefully before submitting your pull request. The requirements clearly mention that the popup should work for all projects in the portfolio section. Additionally, update your portfolio section to dynamically create all projects using a for loop or similar method.
**-In order to associate each project with the popup window details, you must refactor the project section:
o You need to use a JavaScript array to store all of the information for all projects.
o For each project you need to store the following pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, link to source.
o You need to update the main page so that the projects section is created dynamically using the information stored in that JavaScript object. Remember, all of the HTML in that section is created when the page loads.
o After that, you could implement the popup window.
• You should implement popups for both mobile and desktop screen sizes.**

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!
![159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff](https://github.com/Charzy-1/Hello-world/assets/63063973/dcaf3754-f90d-4bb2-ba76-03e5d01a282d)
# Highlights
✔️ Professional Readme
✔️ Correct Gitflow
✔️ Linters pass
## Required 
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@basitali111] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2024-06-19 09:46 UTC, Charzy-1 commented
I have handled the popup which redirects the user to the begining of the page initially. It is fixed now

2024-06-19 11:42 UTC, Pamphilemkp commented on script.js
> +];
- Please add a description paragraph on each card, when they get clicked they should appear the same as shown in the figma design, this is a simple task for you as you added it on the first item in the array as the only thing you can do  is to add the same key in the object called description and you can add some descriptions. with the same length as shown in the figma design.

2024-06-19 12:00 UTC, Pamphilemkp requested changes
## Hi :raising_hand: @Charzy-1 , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!


![](https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif)

## Highlights :green_circle: 


- PR is descriptive and professional :+1: 
- Popup windows are showing correctly and coming at the right position.
- No Linter error :heavy_check_mark: 


## Required Changes ♻️
- Please add a description paragraph on each card, when they get clicked they should appear the same as shown in the figma design, this is a simple task for you as the only thing you can do  is to add a new key in the object called description and you can add some description. Try to work on that.
![Screenshot (286)](https://github.com/Charzy-1/My-Portfolio-Website/assets/98436409/7799db5e-370a-4da0-a78b-d937bff621a5)
![Screenshot (287)](https://github.com/Charzy-1/My-Portfolio-Website/assets/98436409/8a0cad06-2e71-47a4-b9a8-3985ae5838ef)

- The section (My recent works) is overlapping when hitting the break point of about 1030px and above as shown below 
#Your design 
![Screenshot (284)](https://github.com/Charzy-1/My-Portfolio-Website/assets/98436409/d6bbe46c-361e-45aa-b35a-42ca9658b54c)

#Original design
![Screenshot (288)](https://github.com/Charzy-1/My-Portfolio-Website/assets/98436409/de0676b6-dde8-46bb-981d-8c148374eb7f)


_Check the comments under the review._

## Optional suggestions

- The cards after My recent works should only span one row for all the the screens with a fix size lesser than 768px.
![Screenshot (289)](https://github.com/Charzy-1/My-Portfolio-Website/assets/98436409/9ef11f4e-bb0b-4561-afad-0fd80f897b63)



_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the (Code reviews limits policy) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using our Whatsapp Chill Academy Tutoring group

2024-06-19 13:38 UTC, Charzy-1 commented
I have added the description  to the cards. Please check

2024-06-19 13:46 UTC, Pamphilemkp commented
> I have added the description to the cards. Please check
I hope you have implemented all the required changes i have raised

2024-06-19 16:50 UTC, Charzy-1 commented
I have effected the correction

2024-06-19 19:38 UTC, Pamphilemkp requested changes
## Hi :raising_hand: @Charzy-1 , 

Good job so far!
Your project is almost complete however
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!


![](https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExaWN6N3pobDh0MW9zbXo3c3U1eHVyNTl3NzEyZTYyeTZtaTN3Mm1ieiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/KyBesf8kNT6s88SEgb/200.webp)

## Highlights :green_circle: 


- PR is descriptive and professional :+1: 
- Popup windows are showing correctly and coming at the right position.  :heavy_check_mark: 
- Popup description paragraphs have been added successfully  :heavy_check_mark: 
- No Linter error :heavy_check_mark: 


## Required Changes ♻️

- The section (My recent works) is overlapping when hitting the break point of about 1030px and above as shown below 
## Your design 

![Screenshot (284)](https://github.com/Charzy-1/My-Portfolio-Website/assets/98436409/d6bbe46c-361e-45aa-b35a-42ca9658b54c)

## Original design

![Screenshot (288)](https://github.com/Charzy-1/My-Portfolio-Website/assets/98436409/de0676b6-dde8-46bb-981d-8c148374eb7f)

- All the popup cards are showing the same title and image while they should show the clicked title, description and image, only the first card under (My recent works) should show this popup below. Please kindy show the right image, title, description etc. when the user clicks any of the cards.

![Screenshot (290)](https://github.com/Charzy-1/My-Portfolio-Website/assets/98436409/af8b9505-8158-4eca-b280-949b163ae2af)

 You are almost there, the card above should only be displayed for the first card the other remaining ones should the corresponding details.

_Check the comments under the review._

## Optional suggestions

- The cards after My recent works should only span one row for all the the screens with a fix size lesser than 768px.
![Screenshot (289)](https://github.com/Charzy-1/My-Portfolio-Website/assets/98436409/9ef11f4e-bb0b-4561-afad-0fd80f897b63)



_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the (Code reviews limits policy) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using our Whatsapp Chill Academy Tutoring group

2024-06-19 19:40 UTC, Pamphilemkp commented
Please before requesting for a new review make sure you implement the required changes. You are alomst there just repplace the popup cards details with the right ones and also fix the first card under My recent works

2024-06-20 09:55 UTC, Charzy-1 commented
Please check it now. I believe the issues raised has been handled.

2024-06-20 13:24 UTC, Pamphilemkp approved these changes
Hi @Charzy-1 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media3.giphy.com/media/zSzYBsqf6hUkkOM206/200.webp?cid=790b7611g2d958414ykmvnhkok3srn5akb3gvsl9284a4o7a&ep=v1_gifs_search&rid=200.webp&ct=g)


Congratulations! 🎉 
## Highlights
- No linter errors ✅  
- Good Pr title and description 💪🏿 
- The popup window is working 💪🏿 ✅  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


- Please make sure the popup image block and paragraph have  the same height as shown in figma design. So the buttons (See Live & See Source) will end at the same level as the image and the paragraph will start also at the same level as the image block.

## Your design 

![Screenshot (291)](https://github.com/Charzy-1/My-Portfolio-Website/assets/98436409/24b1f36b-9a7a-4edf-997d-74a3fe74ec34)

## Figma design

![Screenshot (292)](https://github.com/Charzy-1/My-Portfolio-Website/assets/98436409/058079f6-f87c-4efc-b1d3-1ac8ce2dfec7)

- The contact me section is overlapping when we hit the breakpoint of  769px to 853px, kindly make sure to fix this issue.
![Screenshot (293)](https://github.com/Charzy-1/My-Portfolio-Website/assets/98436409/1d66034f-ebbd-4fac-af80-56ba6b2e29f5)

- Kindly ensure that your application is deployed,  so users don't have to clone your repository to see your app, kindly checkout github pages.
[Deploy on Github Pages click here](https://www.youtube.com/watch?v=OltY8JIaP-4)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @Pamphilemkp 

------
_As described in the Code reviews limits policy  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, hit us up.

2024-06-20 14:16 UTC, merged